### US ACCIDENTS EXPLORATORY DATA ANALYSIS:

In [1]:
# Imports
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

**Loading the dataset**

Source : *https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents*

Description : 

US-Accidents dataset is a country-wide car accident dataset, covering over 49 states of the USA. The accident data has been collected from February 2016 to December 2021, in real-time.

**Data Preparation and Cleaning:**
1. Load the csv dataset
2. Explore the dataset - some information about the data and columns/features
3. Fix any missing / NULL / incorrect values

In [2]:
# Load the dataset
df = pd.read_csv("../input/us-accidents/US_Accidents_Dec21_updated.csv")
df.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,3,2016-02-08 00:37:08,2016-02-08 06:37:08,40.108910,-83.092860,40.112060,-83.031870,3.230,Between Sawmill Rd/Exit 20 and OH-315/Olentang...,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,2,2016-02-08 05:56:20,2016-02-08 11:56:20,39.865420,-84.062800,39.865010,-84.048730,0.747,At OH-4/OH-235/Exit 41 - Accident.,...,False,False,False,False,False,False,Night,Night,Night,Night
2,A-3,2,2016-02-08 06:15:39,2016-02-08 12:15:39,39.102660,-84.524680,39.102090,-84.523960,0.055,At I-71/US-50/Exit 1 - Accident.,...,False,False,False,False,False,False,Night,Night,Night,Day
3,A-4,2,2016-02-08 06:51:45,2016-02-08 12:51:45,41.062130,-81.537840,41.062170,-81.535470,0.123,At Dart Ave/Exit 21 - Accident.,...,False,False,False,False,False,False,Night,Night,Day,Day
4,A-5,3,2016-02-08 07:53:43,2016-02-08 13:53:43,39.172393,-84.492792,39.170476,-84.501798,0.500,At Mitchell Ave/Exit 6 - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day

In [3]:
# Number of rows(data), Number of columns(features)
df.shape

(2845342, 47)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2845342 entries, 0 to 2845341
Data columns (total 47 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Severity               int64
 2   Start_Time             object
 3   End_Time               object
 4   Start_Lat              float64
 5   Start_Lng              float64
 6   End_Lat                float64
 7   End_Lng                float64
 8   Distance(mi)           float64
 9   Description            object
 10  Number                 float64
 11  Street                 object
 12  Side                   object
 13  City                   object
 14  County                 object
 15  State                  object
 16  Zipcode                object
 17  Country                object
 18  Timezone               object
 19  Airport_Code           object
 20  Weather_Timestamp      object
 21  Temperature(F)         float64
 22  Wind_Chill(F)          float64
 23  Humidity(%)            float64
 24  Pressure(in)           float64
 25  Visibility(mi)         float64
 26  Wind_Direction         object
 27  Wind_Speed(mph)        float64
 28  Precipitation(in)      float64
 29  Weather_Condition      object
 30  Amenity                bool
 31  Bump                   bool
 32  Crossing               bool
 33  Give_Way               bool
 34  Junction               bool
 35  No_Exit                bool
 36  Railway                bool
 37  Roundabout             bool
 38  Station                bool
 39  Stop                   bool
 40  Traffic_Calming        bool
 41  Traffic_Signal         bool
 42  Turning_Loop           bool
 43  Sunrise_Sunset         object
 44  Civil_Twilight         object
 45  Nautical_Twilight      object
 46  Astronomical_Twilight  object
dtypes: bool(13), float64(13), int64(1), object(20)
memory usage: 773.4+ MB

In [5]:
df.describe()

,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Number,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in)
count,2.845342e+06,2.845342e+06,2.845342e+06,2.845342e+06,2.845342e+06,2.845342e+06,1.101431e+06,2.776068e+06,2.375699e+06,2.772250e+06,2.786142e+06,2.774796e+06,2.687398e+06,2.295884e+06
mean,2.137572e+00,3.624520e+01,-9.711463e+01,3.624532e+01,-9.711439e+01,7.026779e-01,8.089408e+03,6.179356e+01,5.965823e+01,6.436545e+01,2.947234e+01,9.099391e+00,7.395044e+00,7.016940e-03
std,4.787216e-01,5.363797e+00,1.831782e+01,5.363873e+00,1.831763e+01,1.560361e+00,1.836009e+04,1.862263e+01,2.116097e+01,2.287457e+01,1.045286e+00,2.717546e+00,5.527454e+00,9.348831e-02
min,1.000000e+00,2.456603e+01,-1.245481e+02,2.456601e+01,-1.245457e+02,0.000000e+00,0.000000e+00,-8.900000e+01,-8.900000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.000000e+00,3.344517e+01,-1.180331e+02,3.344628e+01,-1.180333e+02,5.200000e-02,1.270000e+03,5.000000e+01,4.600000e+01,4.800000e+01,2.931000e+01,1.000000e+01,3.500000e+00,0.000000e+00
50%,2.000000e+00,3.609861e+01,-9.241808e+01,3.609799e+01,-9.241772e+01,2.440000e-01,4.007000e+03,6.400000e+01,6.300000e+01,6.700000e+01,2.982000e+01,1.000000e+01,7.000000e+00,0.000000e+00
75%,2.000000e+00,4.016024e+01,-8.037243e+01,4.016105e+01,-8.037338e+01,7.640000e-01,9.567000e+03,7.600000e+01,7.600000e+01,8.300000e+01,3.001000e+01,1.000000e+01,1.000000e+01,0.000000e+00
max,4.000000e+00,4.900058e+01,-6.711317e+01,4.907500e+01,-6.710924e+01,1.551860e+02,9.999997e+06,1.960000e+02,1.960000e+02,1.000000e+02,5.890000e+01,1.400000e+02,1.087000e+03,2.400000e+01

In [6]:
# Numerical :
df['Precipitation(in)'] = df['Precipitation(in)'].fillna(df['Precipitation(in)'].mean())
df['Wind_Chill(F)'] = df['Wind_Chill(F)'].fillna(df['Wind_Chill(F)'].mean())
df['Wind_Speed(mph)'] = df['Wind_Speed(mph)'].fillna(df['Wind_Speed(mph)'].mean())
df['Temperature(F)'] = df['Temperature(F)'].fillna(df['Temperature(F)'].mean())
df['Humidity(%)'] = df['Humidity(%)'].fillna(df['Humidity(%)'].mean())
df['Visibility(mi)'] = df['Visibility(mi)'].fillna(df['Visibility(mi)'].mean())

# Categorical :
df['Weather_Condition']=df['Weather_Condition'].fillna(df['Weather_Condition'].mode()[0])

In [7]:
# add Duration(min) attribute in replacement of start and end time
df['Start_Time'] = pd.to_datetime(df['Start_Time'])
df['End_Time'] = pd.to_datetime(df['End_Time'])
df['Duration(min)'] = (df['End_Time'] - df['Start_Time']).astype('timedelta64[m]')

In [8]:
df.columns

Index(['ID', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat', 'Start_Lng',
       'End_Lat', 'End_Lng', 'Distance(mi)', 'Description', 'Number', 'Street',
       'Side', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone',
       'Airport_Code', 'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight', 'Duration(min)'],
      dtype='object')

In [9]:
df_new = df.drop(columns = ['Start_Time','End_Time','Description','Number','Street','Side','County','Zipcode','Country','Timezone',
                            'Airport_Code','Civil_Twilight','Nautical_Twilight','Astronomical_Twilight','Weather_Timestamp'])
df_new.head()

,ID,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),City,State,Temperature(F),...,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Duration(min)
0,A-1,3,40.108910,-83.092860,40.112060,-83.031870,3.230,Dublin,OH,42.1,...,False,False,False,False,False,False,False,False,Night,360.0
1,A-2,2,39.865420,-84.062800,39.865010,-84.048730,0.747,Dayton,OH,36.9,...,False,False,False,False,False,False,False,False,Night,360.0
2,A-3,2,39.102660,-84.524680,39.102090,-84.523960,0.055,Cincinnati,OH,36.0,...,False,False,False,False,False,False,False,False,Night,360.0
3,A-4,2,41.062130,-81.537840,41.062170,-81.535470,0.123,Akron,OH,39.0,...,False,False,False,False,False,False,False,False,Night,360.0
4,A-5,3,39.172393,-84.492792,39.170476,-84.501798,0.500,Cincinnati,OH,37.0,...,False,False,False,False,False,False,False,False,Day,360.0

In [10]:
df_new.columns

Index(['ID', 'Severity', 'Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng',
       'Distance(mi)', 'City', 'State', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'Duration(min)'],
      dtype='object')

In [11]:
road_df = df_new.drop(columns=['Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng','Temperature(F)',
       'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)', 'Visibility(mi)',
       'Wind_Direction', 'Wind_Speed(mph)', 'Precipitation(in)',
       'Weather_Condition', 'Sunrise_Sunset'])
road_df.head()

,ID,Severity,Distance(mi),City,State,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Duration(min)
0,A-1,3,3.230,Dublin,OH,False,False,False,False,False,False,False,False,False,False,False,False,False,360.0
1,A-2,2,0.747,Dayton,OH,False,False,False,False,False,False,False,False,False,False,False,False,False,360.0
2,A-3,2,0.055,Cincinnati,OH,False,False,False,False,True,False,False,False,False,False,False,False,False,360.0
3,A-4,2,0.123,Akron,OH,False,False,False,False,False,False,False,False,False,False,False,False,False,360.0
4,A-5,3,0.500,Cincinnati,OH,False,False,False,False,False,False,False,False,False,False,False,False,False,360.0

In [12]:
weather_df = df_new.drop(columns=['Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng','Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop'])
weather_df.head()

,ID,Severity,Distance(mi),City,State,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Sunrise_Sunset,Duration(min)
0,A-1,3,3.230,Dublin,OH,42.1,36.100000,58.0,29.76,10.0,SW,10.400000,0.000000,Light Rain,Night,360.0
1,A-2,2,0.747,Dayton,OH,36.9,59.658231,91.0,29.68,10.0,Calm,7.395044,0.020000,Light Rain,Night,360.0
2,A-3,2,0.055,Cincinnati,OH,36.0,59.658231,97.0,29.70,10.0,Calm,7.395044,0.020000,Overcast,Night,360.0
3,A-4,2,0.123,Akron,OH,39.0,59.658231,55.0,29.65,10.0,Calm,7.395044,0.007017,Overcast,Night,360.0
4,A-5,3,0.500,Cincinnati,OH,37.0,29.800000,93.0,29.69,10.0,WSW,10.400000,0.010000,Light Rain,Day,360.0

**Distribution of Accidents based on Severity (%) :**

We are mostly interested in the correlations between Severity and other attributes : 
- Crossing has negative relationship with severity of weak strength 
- Junction has slightly higher positive relationship with severity
- Most of the attributes have fairly weak and mostly negative correlations with severity
- Railway and Roundabout have very weak correlations with severity

There certain correlations that standout in the heatmap :
*  Traffic_Calming & Bump, Traffic_Signal & Crossing and Railway & Crossing have positive correlation with fair strength

This is to be expected as these road features/conditions are found together.

In [13]:
road_df = road_df.drop(columns=['Railway', 'Roundabout'])

In [14]:
road_df.columns

Index(['ID', 'Severity', 'Distance(mi)', 'City', 'State', 'Amenity', 'Bump',
       'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Station', 'Stop',
       'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop', 'Duration(min)'],
      dtype='object')

In [15]:
weather_df.columns

Index(['ID', 'Severity', 'Distance(mi)', 'City', 'State', 'Temperature(F)',
       'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)', 'Visibility(mi)',
       'Wind_Direction', 'Wind_Speed(mph)', 'Precipitation(in)',
       'Weather_Condition', 'Sunrise_Sunset', 'Duration(min)'],
      dtype='object')

In [ ]:
# subset the dataset region wise
city_df = weather_df.drop(columns=['Distance(mi)','Temperature(F)', ])